language: python
python:
  - "2.7"
env: JMETER_PATH=./
before_script:
  - chmod +x bin/generate_files_from_jtl.sh
  - chmod +x bin/JMeterInstaller.py
script:
  - nosetests -s
  - rm -rf results && mkdir results
  - chmod -R 777 ./
  - apache-jmeter-5.1/bin/jmeter.sh -j results/jmeter.log -p tests/jmeter.properties -t tests/calculator.jmx -n -l results/calculator.jtl
  - home/travis/build/Oswaldo9911/performanceTravisCI/apache-jmeter-5.1/bin
  - sh jmeter -g results/calculator.jtl -o results/JMeterReport/Generate
#notifications:
  #slack: lendingfront:AUFyTKKUAyVMw3cG3un8Y0LY
