language: python
python:
  - "2.7"
env: JMETER_PATH=./

before_script:
  - chmod +x bin/generate_files_from_jtl.sh
  - chmod +x bin/JMeterInstaller.py

script:
  - nosetests -s
  - rm -rf results && mkdir results
  - chmod -R 777 ./
  - apache-jmeter-5.1/bin/jmeter.sh -j results/jmeter.log -p tests/user.properties -t tests/calculator.jmx -n -l results/calculator.csv
  - rm -rf results/JMeterReport && mkdir results/JMeterReport
  - apache-jmeter-5.1/bin/jmeter.sh -g results/calculator.csv -o results/JMeterReport

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY
  bucket: "lf-automated-tests-framework"
  local_dir: /home/travis/build/Oswaldo9911/performanceTravisCI/apache-jmeter-5.1/lib
  upload-dir: performance/

notifications:
  slack:
    - rooms:
        - travis encrypt lendingfront:AUFyTKKUAyVMw3cG3un8Y0LY
      on_success: always
      on_failure: never
      template:
        - "Build details: %{build_url}"