language: python
python:
  - "2.7"
env: JMETER_PATH=./

before_script:
  - chmod +x bin/generate_files_from_jtl.sh
  - chmod +x bin/JMeterInstaller.py

script:
  - nosetests -s
  - rm -rf results && mkdir results
  - chmod -R 777 ./
  - apache-jmeter-5.1/bin/jmeter.sh -j results/jmeter.log -p tests/user.properties -t tests/calculator.jmx -n -l results/calculator.csv
  - rm -rf results/JMeterReport && mkdir results/JMeterReport
  - apache-jmeter-5.1/bin/jmeter.sh -g results/calculator.csv -o results/JMeterReport

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY
  bucket: "lf-automated-tests-framework"
  local_dir: /home/travis/build/Oswaldo9911/performanceTravisCI/results/JMeterReport
  upload_dir: performance
  skip_cleanup: true
  acl: public_read

notifications:
 slack:
  rooms:
   - secure: d14CzswAU2ZCGWBK0paCRhmhjkFdv7BH/WxdSH32xMrn/ZblIPJGmFzQB5hQImXP2YLUX2AcEgRacmLmY9+kpD/lew+j838BjSDCb6P2Afw8EnRqXPo0JE9+9EaSRDEZi2l+oacdtAq23P3VUw6BC1G0kOgYA+5BGjK+tPmw2hyrDhlVjTWGdprdFcJHk9/LfGZmH2tnJhfKqWQMq/mgyjZZfP64/lfV/yEha/PiNMkAG9kFa4Gmj7aOIAGnEuV3IeUYRSWqfx/eFkbTXMYuDg8jft6okxIJkkBG696479zd60BfTvpriYLEYJXZh32d/1fP7U48bY4Wx/Tk120SfJUpRsHpQ1dNbHjsSnl0OcokguwgJst8ez/lNCbFiGo4nnIDORfPbLQc0ttq/FuMz81aNfombLfIRx+UbvA6bnJkiy+Yb7DMKk5UFDhwamNKo7TOC30jKGc/M77/E2Iw6lv8Rj6FerW1IBrvJvbNzr1mibtXbF0LCCoaViLL4NrNYiTQsRcWDgpIuuydzUoKuzdL14L/C3k+HFRdwEBMs3r0OdUnU/lBacQcv+wnzo7kzKXZWf7YK+EXqzdYhz3Xq/tn0eoIl2h0A3YSY0rxPGql0R/UFn72K3gLQcCJFM6Px1kEz2mkG7wrmaGMH9QWRKV2nv/dx4WO+pbQpYbapnY=