language: python
python:
  - "2.7"
env: JMETER_PATH=./

before_script:
  - chmod +x bin/generate_files_from_jtl.sh
  - chmod +x bin/JMeterInstaller.py

script:
  - nosetests -s
  - rm -rf results && mkdir results
  - chmod -R 777 ./
  - apache-jmeter-5.1/bin/jmeter.sh -j results/jmeter.log -p tests/user.properties -t tests/calculator.jmx -n -l results/calculator.csv
  - rm -rf results/JMeterReport && mkdir results/JMeterReport
  - apache-jmeter-5.1/bin/jmeter.sh -g results/calculator.csv -o results/JMeterReport

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY
  bucket: "lf-automated-tests-framework"
  local_dir: /home/travis/build/Oswaldo9911/performanceTravisCI/results/JMeterReport
  upload_dir: performance
  skip_cleanup: true
  acl: public_read

notifications:
  slack:
    rooms:
      - secure: NiJTyH/z75iJURLSztf7v4H7NrHmxRI2UGF9m2D/Bmwrtnda5IPGFlTMNHJgf3xGA2B9dOb6x6HneFLQepA7gBp6OXhlGgv/P7vgC9B1EqIYTEGNS4NGruQPGmFiBb8En5Iy67epADETWlLgO/nK47YE17T1yUdqZrHsLuB/1QjRGNTkR6NgSjbPUKCJ8EWVpp+YQVMwsA6F2sBxGp8YjvR2N6C6o8oVTiCh/BJ/+6HwbDNIdA42+m8W4via8zjA73GIhN123oHgJiBlRlspBpIEprb+jqlN/2hyXKnxPeDESjFhQCvd4CUl+LfM4wi+vG/0ZMiAwEgW4ILR3en9nGOef+D4Dotlq84By0pC0tw1HhRo2R0Dug25murDdp2QlrXpp6liUbX7dHlj4auO9mIJI08+EuWxApCPZqGoUmWOESrp/y4gnv9EdD8uj/ETkG5LIUKtMLylfRMB4B++ghVLNiysi3pur70YMO4tiUZCMjJA9RxcbFAnfi8crlaMeA9BSRPVuHT0zFDq/IuGV0jtH/Bgh935UQzHzGzwnvdZ8Abqsv/o2o7eavMOuvdtdhy7rXetFS+oa9vqcCl8uGYJLSJT6qXzhqeWpDdond2FUebB/sJ44D0D3S3HHZvuz3ti9V+tJvsmSsOTf2r/xwT/ZshZwnYe2EK0CjOll9U=
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Execution time: *%{duration}*"
      - "Message: %{message}"