language: python
python:
  - "2.7"
env: JMETER_PATH=./
before_script:
  - chmod +x bin/generate_files_from_jtl.sh
  - chmod +x bin/JMeterInstaller.py
script:
  - nosetests -s
  - rm -rf results && mkdir results
  - chmod -R 777 ./
  - apache-jmeter-5.1/bin/jmeter.sh -j results/jmeter.log -p tests/user.properties -t tests/calculator.jmx -n -l results/calculator.csv
 # - home/travis/build/Oswaldo9911/performanceTravisCI/apache-jmeter-5.1/bin
  - rm -rf results/JMeterReport && mkdir results/JMeterReport
  - apache-jmeter-5.1/bin/jmeter.sh -g results/calculator.csv -o results/JMeterReport
notifications:
  slack: lendingfront:AUFyTKKUAyVMw3cG3un8Y0LY
  irc:
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Report: pending"
