language: python
python:
  - "2.7"
#env: JMETER_PATH=./

before_script:
  - chmod +x bin/JMeterInstaller.py

script:
  - rm -rf results && mkdir results
  - chmod -R 777 ./
  - apache-jmeter-5.1/bin/jmeter.sh -j results/jmeter.log -p tests/user.properties -t tests/lending_portal_with_parameters.jmx -n -l results/result.csv -Jserver=$URL_TEST -Jtimeout=10000 -Jthreads=1 -JloopCount=1
  - rm -rf results/JMeterReport && mkdir results/JMeterReport
  - apache-jmeter-5.1/bin/jmeter.sh -g results/result.csv -o results/JMeterReport

notifications:
  slack:
      rooms:
        - secure: PPsjWKa0rPudV0i39sWfVurg+aheSg9XgPvcS9MRSSGZuQsgkg6rLWApM1f34cMD0w+b+YiypCD3RtOTwusDMiyfTcCwRqyD/uBrzsq2MOXD8t3l/q7B+4YgfceAMtfB3Kcx9nwLfNYyUZM6KM059kOBbuAwFoLmKXnfEhoH4Xb6Rs4neU/YIZcB03qCCz9fm9TY+5iXXdVu82GAQwttsCT1OpSOihsajwJ0oU68KOIynpFJPUUwJtcZ6XESjiFtpKDfFGYg1AZM/8h9ipozZqKuo8M2glwfByCjm1cdO0JgwZOiablwIvrCYGVR+NzV9D528FP8x0AncCjoz3VUTxPUHIdRiXrD2jFXJ49RaFeo9UtwoMAn0pTHsJTvW/1BnEjuIRdHuiELY8KS5te2JlqQ3bpbSfyHkzlYno8EWju3s+xAqX8QYmJeEsf46ov2jNoCS6BnUwnh/x8J729Qsp2tBQ7OPBAmXZsrsAicGqTC6L0zD/I/Tm2LtXoHAYqDCR9Ff7UqYGRE4uWf1T4Mmh/Pu2VJ/nZarnqSeUOqZZZ8HB2wXQeWTaYDNbOZ5NkrWXOdm6hyu4gFaaeB9wYiWg4tj9uM1VsXsMnribFOI4ajLU8QcXUXyKTKyzGYEsTF2PaTSGbWi5UJC3eJ+B3IvDyMPhbEEkff97yIzefDuco=
      on_success: always
      on_failure: change
      template:
        - "Results Performance Test Test : lp-search-consult (<https://lf-automated-tests-framework.s3.amazonaws.com/performance/index.html|log>) by %{author} %{result} in %{duration}"

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_ACCESS_KEY
  bucket: "lf-automated-tests-framework"
  local_dir: /home/travis/build/Oswaldo9911/performanceTravisCI/results/JMeterReport
  upload_dir: performance
  skip_cleanup: true
  acl: public_read